export type CaseRewardRarityName = 'common' | 'rare' | 'epic' | 'legendary';

export type GiftTypeDefinition = {
  id: string;
  telegramGiftTypeId?: string;
  name: string;
  description?: string;
  image: string;
  rarity: CaseRewardRarityName;
  estimatedValueTon: number;
  valueLabel: string;
  accent: string;
  textColor: string;
};

export type CaseDropDefinition = {
  id: string;
  giftTypeId: string;
  chance: number;
  sortOrder: number;
};

export type CaseCatalogEntry = {
  id: string;
  slug: string;
  name: string;
  tagline: string;
  shortDescription: string;
  priceTon: number;
  image: string;
  badgeGradient: string;
  buttonGradient: string;
  surfaceTint: string;
  sortOrder: number;
  drops: CaseDropDefinition[];
};

export const GIFT_TYPE_CATALOG: GiftTypeDefinition[] = [
  {
    id: 'starter-rose',
    name: 'Rose Bloom',
    image: '/images/07.png',
    rarity: 'common',
    estimatedValueTon: 4,
    valueLabel: 'Soft drop',
    accent: 'linear-gradient(135deg, #ffe2e2 0%, #ffb4b4 100%)',
    textColor: '#4a1111',
  },
  {
    id: 'starter-sweet',
    name: 'Sweet Spin',
    image: '/images/12.png',
    rarity: 'common',
    estimatedValueTon: 6,
    valueLabel: 'Candy gift',
    accent: 'linear-gradient(135deg, #fff6bf 0%, #ffd970 100%)',
    textColor: '#4f3500',
  },
  {
    id: 'starter-bloom',
    name: 'Cherry Bloom',
    image: '/images/13.png',
    rarity: 'rare',
    estimatedValueTon: 12,
    valueLabel: 'Seasonal drop',
    accent: 'linear-gradient(135deg, #ffe6fa 0%, #ffb5e8 100%)',
    textColor: '#5a1f4d',
  },
  {
    id: 'starter-heart',
    name: 'Ribbon Heart',
    image: '/images/10.png',
    rarity: 'rare',
    estimatedValueTon: 15,
    valueLabel: 'Love token',
    accent: 'linear-gradient(135deg, #ffe0ef 0%, #ff7ab8 100%)',
    textColor: '#591437',
  },
  {
    id: 'starter-gift',
    name: 'Golden Box',
    image: '/images/08.png',
    rarity: 'epic',
    estimatedValueTon: 22,
    valueLabel: 'Wrapped prize',
    accent: 'linear-gradient(135deg, #fff0be 0%, #ffb347 100%)',
    textColor: '#5c3000',
  },
  {
    id: 'starter-ring',
    name: 'Silver Ring',
    image: '/images/02.png',
    rarity: 'legendary',
    estimatedValueTon: 35,
    valueLabel: 'Rare jewel',
    accent: 'linear-gradient(135deg, #f0f8ff 0%, #96d2ff 100%)',
    textColor: '#11395d',
  },
  {
    id: 'mystery-bear',
    name: 'Cozy Bear',
    image: '/images/09.png',
    rarity: 'common',
    estimatedValueTon: 8,
    valueLabel: 'Cute collectible',
    accent: 'linear-gradient(135deg, #f1dfbd 0%, #cfa065 100%)',
    textColor: '#4f3318',
  },
  {
    id: 'mystery-cake',
    name: 'Party Cake',
    image: '/images/11.png',
    rarity: 'common',
    estimatedValueTon: 10,
    valueLabel: 'Celebration drop',
    accent: 'linear-gradient(135deg, #ffe2f0 0%, #ffb2cf 100%)',
    textColor: '#5d2241',
  },
  {
    id: 'mystery-gift',
    name: 'Gift Crate',
    image: '/images/08.png',
    rarity: 'rare',
    estimatedValueTon: 18,
    valueLabel: 'Surprise box',
    accent: 'linear-gradient(135deg, #fff0bb 0%, #ffca55 100%)',
    textColor: '#5f3900',
  },
  {
    id: 'mystery-heart',
    name: 'Velvet Heart',
    image: '/images/10.png',
    rarity: 'rare',
    estimatedValueTon: 20,
    valueLabel: 'Warm charm',
    accent: 'linear-gradient(135deg, #ffd6e8 0%, #ff7fbf 100%)',
    textColor: '#61163e',
  },
  {
    id: 'mystery-gem',
    name: 'Blue Gem',
    image: '/images/01.png',
    rarity: 'epic',
    estimatedValueTon: 32,
    valueLabel: 'Spark drop',
    accent: 'linear-gradient(135deg, #d9f3ff 0%, #7ad1ff 100%)',
    textColor: '#103d5c',
  },
  {
    id: 'mystery-trophy',
    name: 'Golden Cup',
    image: '/images/03.png',
    rarity: 'legendary',
    estimatedValueTon: 45,
    valueLabel: 'Prestige win',
    accent: 'linear-gradient(135deg, #fff2b2 0%, #ffb300 100%)',
    textColor: '#4b3000',
  },
  {
    id: 'premium-gem',
    name: 'Sky Diamond',
    image: '/images/01.png',
    rarity: 'rare',
    estimatedValueTon: 30,
    valueLabel: 'Premium shard',
    accent: 'linear-gradient(135deg, #e5f7ff 0%, #8bcfff 100%)',
    textColor: '#0f3957',
  },
  {
    id: 'premium-ring',
    name: 'Diamond Ring',
    image: '/images/02.png',
    rarity: 'rare',
    estimatedValueTon: 34,
    valueLabel: 'Jewelry drop',
    accent: 'linear-gradient(135deg, #ecf6ff 0%, #b5d9ff 100%)',
    textColor: '#153c5d',
  },
  {
    id: 'premium-heart',
    name: 'Royal Heart',
    image: '/images/10.png',
    rarity: 'epic',
    estimatedValueTon: 52,
    valueLabel: 'Rare charm',
    accent: 'linear-gradient(135deg, #ffe0f1 0%, #ff89c0 100%)',
    textColor: '#5b1b40',
  },
  {
    id: 'premium-cup',
    name: 'Champion Cup',
    image: '/images/03.png',
    rarity: 'epic',
    estimatedValueTon: 60,
    valueLabel: 'Glory item',
    accent: 'linear-gradient(135deg, #fff0ba 0%, #ffcf4d 100%)',
    textColor: '#543200',
  },
  {
    id: 'premium-bloom',
    name: 'Sakura Glow',
    image: '/images/13.png',
    rarity: 'legendary',
    estimatedValueTon: 78,
    valueLabel: 'Festival ultra',
    accent: 'linear-gradient(135deg, #ffe8fb 0%, #ffa1e1 100%)',
    textColor: '#5d2850',
  },
  {
    id: 'premium-bear',
    name: 'Velvet Bear',
    image: '/images/09.png',
    rarity: 'legendary',
    estimatedValueTon: 92,
    valueLabel: 'Collector ultra',
    accent: 'linear-gradient(135deg, #f5e7c2 0%, #dba160 100%)',
    textColor: '#4f3114',
  },
  {
    id: 'blossom-petal',
    name: 'Petal Bloom',
    image: '/images/13.png',
    rarity: 'common',
    estimatedValueTon: 18,
    valueLabel: 'Bloom token',
    accent: 'linear-gradient(135deg, #ffe9f8 0%, #ffc2e7 100%)',
    textColor: '#63244a',
  },
  {
    id: 'blossom-rose',
    name: 'Rose Deluxe',
    image: '/images/07.png',
    rarity: 'rare',
    estimatedValueTon: 32,
    valueLabel: 'Romance drop',
    accent: 'linear-gradient(135deg, #ffe2e2 0%, #ff9b9b 100%)',
    textColor: '#571a1a',
  },
  {
    id: 'blossom-heart',
    name: 'Cupid Heart',
    image: '/images/10.png',
    rarity: 'rare',
    estimatedValueTon: 34,
    valueLabel: 'Ribbon charm',
    accent: 'linear-gradient(135deg, #ffe2f1 0%, #ff87bf 100%)',
    textColor: '#5d1e43',
  },
  {
    id: 'blossom-cake',
    name: 'Pink Cake',
    image: '/images/11.png',
    rarity: 'epic',
    estimatedValueTon: 46,
    valueLabel: 'Party item',
    accent: 'linear-gradient(135deg, #ffe6f5 0%, #ffb0d1 100%)',
    textColor: '#622845',
  },
  {
    id: 'blossom-gem',
    name: 'Love Gem',
    image: '/images/01.png',
    rarity: 'epic',
    estimatedValueTon: 58,
    valueLabel: 'Blue sparkle',
    accent: 'linear-gradient(135deg, #ddf5ff 0%, #84d4ff 100%)',
    textColor: '#103b5a',
  },
  {
    id: 'blossom-ring',
    name: 'Promise Ring',
    image: '/images/02.png',
    rarity: 'legendary',
    estimatedValueTon: 88,
    valueLabel: 'Heart ultra',
    accent: 'linear-gradient(135deg, #f0f8ff 0%, #aed7ff 100%)',
    textColor: '#163d5f',
  },
  {
    id: 'legendary-cup',
    name: 'Legend Cup',
    image: '/images/03.png',
    rarity: 'rare',
    estimatedValueTon: 48,
    valueLabel: 'Prestige prize',
    accent: 'linear-gradient(135deg, #fff0bf 0%, #ffc533 100%)',
    textColor: '#5b3500',
  },
  {
    id: 'legendary-ring',
    name: 'Crystal Ring',
    image: '/images/02.png',
    rarity: 'rare',
    estimatedValueTon: 54,
    valueLabel: 'Crown jewel',
    accent: 'linear-gradient(135deg, #ebf7ff 0%, #9bd1ff 100%)',
    textColor: '#153d60',
  },
  {
    id: 'legendary-gem',
    name: 'Grand Diamond',
    image: '/images/01.png',
    rarity: 'epic',
    estimatedValueTon: 80,
    valueLabel: 'Vault reward',
    accent: 'linear-gradient(135deg, #e2f5ff 0%, #74caff 100%)',
    textColor: '#123d5e',
  },
  {
    id: 'legendary-gift',
    name: 'Royal Present',
    image: '/images/08.png',
    rarity: 'epic',
    estimatedValueTon: 86,
    valueLabel: 'Wrapped vault',
    accent: 'linear-gradient(135deg, #fff3bf 0%, #ffbf3e 100%)',
    textColor: '#583200',
  },
  {
    id: 'legendary-heart',
    name: 'Golden Heart',
    image: '/images/10.png',
    rarity: 'legendary',
    estimatedValueTon: 120,
    valueLabel: 'Ultra charm',
    accent: 'linear-gradient(135deg, #ffe2ee 0%, #ff76b4 100%)',
    textColor: '#601c3d',
  },
  {
    id: 'legendary-bear',
    name: 'Hero Bear',
    image: '/images/09.png',
    rarity: 'legendary',
    estimatedValueTon: 132,
    valueLabel: 'Collector ultra',
    accent: 'linear-gradient(135deg, #f5e4bf 0%, #d49753 100%)',
    textColor: '#4d3015',
  },
  {
    id: 'royal-ring',
    name: 'Royal Ring',
    image: '/images/02.png',
    rarity: 'rare',
    estimatedValueTon: 85,
    valueLabel: 'Elite jewel',
    accent: 'linear-gradient(135deg, #eff8ff 0%, #b4dcff 100%)',
    textColor: '#153f63',
  },
  {
    id: 'royal-gem',
    name: 'Imperial Diamond',
    image: '/images/01.png',
    rarity: 'epic',
    estimatedValueTon: 115,
    valueLabel: 'Vault gem',
    accent: 'linear-gradient(135deg, #dff6ff 0%, #6fcbff 100%)',
    textColor: '#103a59',
  },
  {
    id: 'royal-cup',
    name: 'Victory Trophy',
    image: '/images/03.png',
    rarity: 'epic',
    estimatedValueTon: 128,
    valueLabel: 'Winner relic',
    accent: 'linear-gradient(135deg, #fff0c2 0%, #ffc234 100%)',
    textColor: '#573400',
  },
  {
    id: 'royal-heart',
    name: 'Royal Heart',
    image: '/images/10.png',
    rarity: 'legendary',
    estimatedValueTon: 165,
    valueLabel: 'Luxury charm',
    accent: 'linear-gradient(135deg, #ffe0ee 0%, #ff75b0 100%)',
    textColor: '#631d40',
  },
  {
    id: 'royal-bloom',
    name: 'Empress Bloom',
    image: '/images/13.png',
    rarity: 'legendary',
    estimatedValueTon: 175,
    valueLabel: 'Seasonal ultra',
    accent: 'linear-gradient(135deg, #ffe8fb 0%, #ff9ce0 100%)',
    textColor: '#5e2752',
  },
  {
    id: 'royal-bear',
    name: 'Royal Bear',
    image: '/images/09.png',
    rarity: 'legendary',
    estimatedValueTon: 190,
    valueLabel: 'Mythic plush',
    accent: 'linear-gradient(135deg, #f5e5c2 0%, #d89c58 100%)',
    textColor: '#4d3217',
  },
];

export const CASE_CATALOG: CaseCatalogEntry[] = [
  {
    id: 'starter-case',
    slug: 'starter-case',
    name: 'Starter Case',
    tagline: 'Open for 10 TON',
    shortDescription: 'Friendly drops with bright collectibles and gift staples.',
    priceTon: 10,
    image: '/images/08.png',
    badgeGradient: 'linear-gradient(135deg, #2d7df6 0%, #18c7ea 100%)',
    buttonGradient: 'linear-gradient(90deg, #1b8cf3 0%, #1ec7dc 100%)',
    surfaceTint: '#ddf4ff',
    sortOrder: 0,
    drops: [
      { id: 'starter-case-drop-rose', giftTypeId: 'starter-rose', chance: 28, sortOrder: 0 },
      { id: 'starter-case-drop-sweet', giftTypeId: 'starter-sweet', chance: 24, sortOrder: 1 },
      { id: 'starter-case-drop-bloom', giftTypeId: 'starter-bloom', chance: 18, sortOrder: 2 },
      { id: 'starter-case-drop-heart', giftTypeId: 'starter-heart', chance: 14, sortOrder: 3 },
      { id: 'starter-case-drop-gift', giftTypeId: 'starter-gift', chance: 10, sortOrder: 4 },
      { id: 'starter-case-drop-ring', giftTypeId: 'starter-ring', chance: 6, sortOrder: 5 },
    ],
  },
  {
    id: 'mystery-case',
    slug: 'mystery-case',
    name: 'Mystery Case',
    tagline: 'Open for 25 TON',
    shortDescription: 'Unexpected pulls with playful odds and hidden premium gems.',
    priceTon: 25,
    image: '/images/12.png',
    badgeGradient: 'linear-gradient(135deg, #00c853 0%, #06d6a0 100%)',
    buttonGradient: 'linear-gradient(90deg, #00b85b 0%, #13d0a5 100%)',
    surfaceTint: '#dcffe7',
    sortOrder: 1,
    drops: [
      { id: 'mystery-case-drop-bear', giftTypeId: 'mystery-bear', chance: 22, sortOrder: 0 },
      { id: 'mystery-case-drop-cake', giftTypeId: 'mystery-cake', chance: 20, sortOrder: 1 },
      { id: 'mystery-case-drop-gift', giftTypeId: 'mystery-gift', chance: 18, sortOrder: 2 },
      { id: 'mystery-case-drop-heart', giftTypeId: 'mystery-heart', chance: 16, sortOrder: 3 },
      { id: 'mystery-case-drop-gem', giftTypeId: 'mystery-gem', chance: 14, sortOrder: 4 },
      { id: 'mystery-case-drop-trophy', giftTypeId: 'mystery-trophy', chance: 10, sortOrder: 5 },
    ],
  },
  {
    id: 'premium-case',
    slug: 'premium-case',
    name: 'Premium Case',
    tagline: 'Open for 50 TON',
    shortDescription: 'Shiny gems, rich cosmetics and better premium hit rates.',
    priceTon: 50,
    image: '/images/01.png',
    badgeGradient: 'linear-gradient(135deg, #a137ff 0%, #ff4db7 100%)',
    buttonGradient: 'linear-gradient(90deg, #9d42ff 0%, #ff2fa2 100%)',
    surfaceTint: '#f8e3ff',
    sortOrder: 2,
    drops: [
      { id: 'premium-case-drop-gem', giftTypeId: 'premium-gem', chance: 28, sortOrder: 0 },
      { id: 'premium-case-drop-ring', giftTypeId: 'premium-ring', chance: 24, sortOrder: 1 },
      { id: 'premium-case-drop-heart', giftTypeId: 'premium-heart', chance: 18, sortOrder: 2 },
      { id: 'premium-case-drop-cup', giftTypeId: 'premium-cup', chance: 14, sortOrder: 3 },
      { id: 'premium-case-drop-bloom', giftTypeId: 'premium-bloom', chance: 10, sortOrder: 4 },
      { id: 'premium-case-drop-bear', giftTypeId: 'premium-bear', chance: 6, sortOrder: 5 },
    ],
  },
  {
    id: 'blossom-case',
    slug: 'blossom-case',
    name: 'Blossom Case',
    tagline: 'Open for 75 TON',
    shortDescription: 'Seasonal florals, ribbons and soft luxury rewards.',
    priceTon: 75,
    image: '/images/13.png',
    badgeGradient: 'linear-gradient(135deg, #ff7ab6 0%, #ffb5d6 100%)',
    buttonGradient: 'linear-gradient(90deg, #ff6ca9 0%, #ff9ccc 100%)',
    surfaceTint: '#ffe3ef',
    sortOrder: 3,
    drops: [
      { id: 'blossom-case-drop-petal', giftTypeId: 'blossom-petal', chance: 26, sortOrder: 0 },
      { id: 'blossom-case-drop-rose', giftTypeId: 'blossom-rose', chance: 24, sortOrder: 1 },
      { id: 'blossom-case-drop-heart', giftTypeId: 'blossom-heart', chance: 18, sortOrder: 2 },
      { id: 'blossom-case-drop-cake', giftTypeId: 'blossom-cake', chance: 14, sortOrder: 3 },
      { id: 'blossom-case-drop-gem', giftTypeId: 'blossom-gem', chance: 10, sortOrder: 4 },
      { id: 'blossom-case-drop-ring', giftTypeId: 'blossom-ring', chance: 8, sortOrder: 5 },
    ],
  },
  {
    id: 'legendary-case',
    slug: 'legendary-case',
    name: 'Legendary Case',
    tagline: 'Open for 100 TON',
    shortDescription: 'Top-shelf trophies, rare gems and prestige collector items.',
    priceTon: 100,
    image: '/images/03.png',
    badgeGradient: 'linear-gradient(135deg, #ffb100 0%, #ff6f00 100%)',
    buttonGradient: 'linear-gradient(90deg, #ffb300 0%, #ff7a00 100%)',
    surfaceTint: '#fff1d5',
    sortOrder: 4,
    drops: [
      { id: 'legendary-case-drop-cup', giftTypeId: 'legendary-cup', chance: 26, sortOrder: 0 },
      { id: 'legendary-case-drop-ring', giftTypeId: 'legendary-ring', chance: 22, sortOrder: 1 },
      { id: 'legendary-case-drop-gem', giftTypeId: 'legendary-gem', chance: 18, sortOrder: 2 },
      { id: 'legendary-case-drop-gift', giftTypeId: 'legendary-gift', chance: 14, sortOrder: 3 },
      { id: 'legendary-case-drop-heart', giftTypeId: 'legendary-heart', chance: 12, sortOrder: 4 },
      { id: 'legendary-case-drop-bear', giftTypeId: 'legendary-bear', chance: 8, sortOrder: 5 },
    ],
  },
  {
    id: 'royal-case',
    slug: 'royal-case',
    name: 'Royal Case',
    tagline: 'Open for 200 TON',
    shortDescription: 'The highest tier chest with luxe drops and elite odds.',
    priceTon: 200,
    image: '/images/02.png',
    badgeGradient: 'linear-gradient(135deg, #ff2a5a 0%, #ff7f11 100%)',
    buttonGradient: 'linear-gradient(90deg, #ff2e63 0%, #ff7f11 100%)',
    surfaceTint: '#ffe3da',
    sortOrder: 5,
    drops: [
      { id: 'royal-case-drop-ring', giftTypeId: 'royal-ring', chance: 24, sortOrder: 0 },
      { id: 'royal-case-drop-gem', giftTypeId: 'royal-gem', chance: 22, sortOrder: 1 },
      { id: 'royal-case-drop-cup', giftTypeId: 'royal-cup', chance: 18, sortOrder: 2 },
      { id: 'royal-case-drop-heart', giftTypeId: 'royal-heart', chance: 14, sortOrder: 3 },
      { id: 'royal-case-drop-bloom', giftTypeId: 'royal-bloom', chance: 12, sortOrder: 4 },
      { id: 'royal-case-drop-bear', giftTypeId: 'royal-bear', chance: 10, sortOrder: 5 },
    ],
  },
];

export function getCaseCatalogEntry(slug: string) {
  return CASE_CATALOG.find((caseItem) => caseItem.slug === slug);
}
